### ISSUE TITLE
Message definition for message types with multiple variables

### ISSUE THREAD

**Issue by lowitz** [chalmersfsd/cfsd-message-controller#1]
Want to be able to send e.g. aimPoints (ID = 1172) which has multiple variables within the message

**Comment by wangroger0801** [comment]
Yes, the new message is now available! Variables are split by "|" And sorted by the order definition in OpenDLV messages sets.
In this case: 
opendlv.logic.action.AimPoint
azimuthAngle|zenithAngle|distance
input will be: 0.0|0.0|0.0 
(Just try it. this format is set as the default value) 
:)

**Comment by lowitz** [comment]
Works great :)
